### ISSUE TITLE
提个建议，那个 Loading 的 fade in fade out 效果能不能去掉或者做个开关？

### ISSUE THREAD

**Issue by coolsnowwolf** [rosywrt/luci-theme-rosy#12]
提个建议，那个 Loading 的 fade in fade out 效果能不能去掉或者做个开关？

因为在打开内容较多的页面实在是太慢了，例如 /cgi-bin/luci/admin/status/iptables ， 十几秒才能看到画面

**Comment by rosysong** [comment]
我们也注意到这个问题， 谢谢， 会认真考虑
