### ISSUE TITLE
表格显示异常

### ISSUE THREAD

**Issue by chenhw2** [rosywrt/luci-theme-rosy#13]
feature or bug?

![2018-10-27](https://user-images.githubusercontent.com/12322033/47588508-f268a200-d998-11e8-846d-10efd19738bf.png)

**Comment by rosysong** [comment]
这个固件引用的rosy主题是luci-theme-rosy还是RosyWrt/luci ???

**Comment by chenhw2** [comment]
如图所示 LEDE v17.01.6 with luci-theme-rosy

**Comment by rosysong** [comment]
@chenhw2 哦哦， 抱歉， 建议使用openwrt-18.06. 我们目前是针对这个分支适配的
