### ISSUE TITLE
上移下移按钮为白色

### ISSUE THREAD

**Issue by cc5771027** [rosywrt/luci-theme-rosy#21]
如下:
![png](https://i.loli.net/2018/11/24/5bf8772e5b996.png)

取消cascade.css中如下样式后恢复正常
https://github.com/rosywrt/luci-theme-rosy/blob/1f70fb59b2268fedf9696a394024c4df0e934242/htdocs/luci-static/rosy/cascade.css#L703-L706

**Comment by rosysong** [comment]
fixed, thanks!

**Comment by CCnut** [comment]
现在背景颜色和字体颜色一样了
![image](https://user-images.githubusercontent.com/7758904/49233776-b0b49680-f431-11e8-9d9a-97906102bd70.png)
