### ISSUE TITLE
Memory - No values

### ISSUE THREAD

**Issue by davidc502** [rosywrt/luci-theme-rosy#22]
Currently, Rosy is not showing any Memory values. 

![screenshot from 2018-11-25 20-51-06](https://user-images.githubusercontent.com/14110206/48990461-264bfa00-f0f4-11e8-968c-5ece78cb858c.png)

**Comment by rosysong** [comment]
fixed in master, thanks for reporting!

**Comment by davidc502** [comment]
This issue still persists in r8614

**Comment by davidc502** [comment]
Someone on the forum pointed out if the curser is on the bar the value does show.  It is the bar/graph that is not working correctly.

**Comment by rosysong** [comment]
The newer commit has been merged, you can try it on latest version.  @davidc502

**Comment by davidc502** [comment]
I should be able to test tomorrow and close this issue.

**Comment by davidc502** [comment]
The issue is fixed in r8662.

Thank you
