### ISSUE TITLE
Screen Format Issue

### ISSUE THREAD

**Issue by davidc502** [rosywrt/luci-theme-rosy#24]
Network > Intrerfaces > LAN > Physical Settings

Under "Enable IGMP Snooping" there is the Interface dropdown box. Currently the dropdown box is blocked by the size of the general window.  See below screenshot.

![screenshot from 2018-11-27 07-25-42](https://user-images.githubusercontent.com/14110206/49084855-3fe56280-f216-11e8-9503-f5c8f40ebdb8.png)

**Comment by Keltere** [comment]
Also on dhcp page
![capture](https://user-images.githubusercontent.com/8084245/49119808-37d70280-f2aa-11e8-85d0-f0ea9ff86383.JPG)

**Comment by davidc502** [comment]
I see where it is being cut off.  A work around will be to add a line below it, and then the dropdown will work on the line above.

**Comment by rosysong** [comment]
fixed, please update the latest version and close the issue. Thanks

**Comment by rosysong** [comment]
@davidc502

**Comment by davidc502** [comment]
Understood --  I will be changing the default theme to Rosy for all davidc502 builds.  I will start working on a new build on the 31st (Saturday).  Will test then and close.

**Comment by blamaz** [comment]
> Understood -- I will be changing the default theme to Rosy for all davidc502 builds. I will start working on a new build on the 31st (Saturday). Will test then and close.

You mean 1st of december (no 31st in november) :)

**Comment by davidc502** [comment]
The issue has been resolved. Confirmed fixed in build r8614.
