### ISSUE TITLE
Incorrectly displayed /cgi-bin/luci/admin/status/iptables

### ISSUE THREAD

**Issue by spawnlmg** [rosywrt/luci-theme-rosy#26]
![image](https://user-images.githubusercontent.com/23347625/49340415-1c704c80-f648-11e8-960f-98cf52fa9b03.png)

these rules are added and work, but not displayed

iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 195.82.146.214 -j zone_wan_dest_ACCEPT -m comment --comment "rutracker.org, rutracker.net, rutracker.lib"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 195.82.146.114 -j zone_wan_dest_ACCEPT -m comment --comment "rutracker.cr"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 104.28.17.16 -j zone_wan_dest_ACCEPT -m comment --comment "rutracker.nl"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 104.28.16.16 -j zone_wan_dest_ACCEPT -m comment --comment "rutracker.nl"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 195.82.146.121 -j zone_wan_dest_ACCEPT -m comment --comment "bt2.t-ru.org"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 195.82.146.122 -j zone_wan_dest_ACCEPT -m comment --comment "bt3.t-ru.org"
iptables -A zone_vpn_server_2_forward -s 10.20.0.0/16 -d 195.82.146.123 -j zone_wan_dest_ACCEPT -m comment --comment "bt4.t-ru.org"

**Comment by rosysong** [comment]
@spawnlmg Does other themes have this issue as well ??

**Comment by rosysong** [comment]
The newer commit has been merged, you can try it on latest version.
