### ISSUE TITLE
 Screen format issue in Network Shares

### ISSUE THREAD

**Issue by blamaz** [rosywrt/luci-theme-rosy#28]
I have a screen format issue in the Network Shares settings, fields name and path are too small to input data. I'm using luci-theme-rosy_git-18.333.34665-4f2b80e-1 on davidc r8373. Also, the Shared Directories delete icon is partially cut off the screen when viewed in google chrome.
![image](https://user-images.githubusercontent.com/33003276/49702961-2f959600-fbcd-11e8-9512-377de9224e8d.png)

**Comment by yglb** [comment]
Can you tell me which interface is this?
@blamaz

**Comment by davidc502** [comment]
This build is also from the Master development branch.

**Comment by davidc502** [comment]
Is Rosy being actively developed? It seemed it was being worked on regularly in the past?

**Comment by rosysong** [comment]
https://github.com/openwrt/luci/pull/2367, we fixed relevant issue in master branch. 
Does it work fine now ??

**Comment by davidc502** [comment]
It is working now -- Thank you
