### ISSUE TITLE
Screen Format Issue in Software

### ISSUE THREAD

**Issue by davidc502** [rosywrt/luci-theme-rosy#29]
When in the software section and clicking "Update Lists", much of the text is observed behind the menu.

![screenshot from 2018-12-09 17-22-30](https://user-images.githubusercontent.com/14110206/49704399-0fb79f80-fbd8-11e8-8677-52156636caf0.png)

**Comment by yglb** [comment]
![image](https://user-images.githubusercontent.com/39110824/49708546-0592b100-fc6b-11e8-94ab-bbc11872a10f.png)

**Comment by davidc502** [comment]
Is Rosy being actively developed? It seemed it was being worked on regularly in the past?

**Comment by rosysong** [comment]
@davidc502   How about this issue ?

**Comment by davidc502** [comment]
This appears to be fixed in the latest build.  Thank you
