### ISSUE TITLE
Screen Format Issue - Configure opkg

### ISSUE THREAD

**Issue by davidc502** [rosywrt/luci-theme-rosy#30]
Clicking "Configure opkg" in the software section the user is presented text at the bottom of the page. the values are hidden behind the left hand menu and are not editable.

![screenshot from 2018-12-09 17-47-56](https://user-images.githubusercontent.com/14110206/49704614-cae13800-fbda-11e8-8344-d462b36062a7.png)

**Comment by yglb** [comment]
I want to ask, is this a problem under the 18.06 branch? 
Which interface is this?
@davidc502

**Comment by davidc502** [comment]
Master Development Branch.
Lede SNAPSHOT r8662-02494fa35c / LuCI Master (git-18.340.83538-1b26c91)

**Comment by davidc502** [comment]
Is Rosy being actively developed? It seemed it was being worked on regularly in the past?
This issue can be closed.
