### ISSUE TITLE
主题显示不正常

### ISSUE THREAD

**Issue by inlyt** [rosywrt/luci-theme-rosy#31]
界面不匹配
![1](https://user-images.githubusercontent.com/35872517/49878557-d6df2b00-fe62-11e8-8fd3-aeb70767517d.png)
![2](https://user-images.githubusercontent.com/35872517/49878558-d6df2b00-fe62-11e8-9089-1af9e0a0c1c6.png)
![3](https://user-images.githubusercontent.com/35872517/49878559-d777c180-fe62-11e8-9a7c-f0df85fd5303.png)
![4](https://user-images.githubusercontent.com/35872517/49878560-d8105800-fe62-11e8-8fd9-9279f6ee1b8c.png)
![5](https://user-images.githubusercontent.com/35872517/49878561-d8105800-fe62-11e8-98a3-e00c00baf7b1.png)
![7](https://user-images.githubusercontent.com/35872517/49878564-d8a8ee80-fe62-11e8-80b4-d9f20c37ed92.png)
![8](https://user-images.githubusercontent.com/35872517/49878565-d8a8ee80-fe62-11e8-8f2f-07a9e528529f.png)
![9](https://user-images.githubusercontent.com/35872517/49878567-d9418500-fe62-11e8-9325-5ca8049d90bb.png)
![10](https://user-images.githubusercontent.com/35872517/49878568-da72b200-fe62-11e8-8f73-ba575076e01b.png)

**Comment by rosysong** [comment]
@inlyt  抱歉， 请用OpenWrt官方SDK， 其余SDK我们暂不维护。
https://github.com/openwrt
