### ISSUE TITLE
上移下移字符与按钮同色

### ISSUE THREAD

**Issue by CCnut** [rosywrt/luci-theme-rosy#33]
![image](https://user-images.githubusercontent.com/7758904/49233776-b0b49680-f431-11e8-9d9a-97906102bd70.png)

_Originally posted by @cc5771027 in https://github.com/rosywrt/luci-theme-rosy/issues/21#issuecomment-442884242_

**Comment by yglb** [comment]
please update @cc5771027

**Comment by CCnut** [comment]
我昨天用openwrt-18.06分支新编译的，已经是最新了
![image](https://user-images.githubusercontent.com/7758904/50062424-21a1cf80-01e2-11e9-889a-72eb11ecf8ad.png)

**Comment by rosysong** [comment]
@cc5771027  请确认问题是否解决了， 谢谢

**Comment by CCnut** [comment]
用master分支编译了一个没问题了
