### ISSUE TITLE
Scroll Bar on Sidebar when using Firefox, IE11 and MS Edge

### ISSUE THREAD

**Issue by boktai1000** [rosywrt/luci-theme-rosy#34]
Hello,

When using the latest version of your Rosy theme I have noticed that in Firefox (and IE11) that there is a scrollbar shown when in the interface. This scrollbar is not present when using Google Chrome. I've tested this on both OpenWrt 18.06.1 and current Snapshots and can confirm behavior in both versions. Firefox and IE11 are the only two browsers which I can confirm where this is happening.

Operating System: Windows 10 x64 (Build 1809 - October 2018)
Browser: Firefox (Latest), Internet Explorer 11, Microsoft Edge
OpenWrt Version:  OpenWrt SNAPSHOT r8875-a28f6ab / LuCI Master (git-18.360.62454-8274ebf) 
Rosy Version: git-18.356.64384-31d259a-1

Please see the screenshot example here where I've outlined the scrollbar in question, you cannot interact with it as mentioned. Replicating this should be as easy as attempting to use Rosy with Firefox or IE11 as behavior is identical between them.

Edit: I've also had the chance to test Microsoft Edge and can confirm that Edge also exhibits the same behavior with displaying the Scroll Bar, so I've added it to the list of browsers.

![image](https://user-images.githubusercontent.com/9054563/50462256-a1017280-0949-11e9-92e4-27a82ca0a677.png)

**Comment by boktai1000** [comment]
I may have misunderstood the reason why it was there, as I now see that Google Chrome supports a mobile or rather compact user interface when the browser interface shrinks, but these browsers that I listed (Firefox, Edge, IE11) do not support that interface, and instead make use of this scroll bar which later does become usable.

If you could confirm this is intended functionality that would be great. Is there also a reason why the mobile user interface only works in one browser - one would assume that the compatibility should exist across the board.

**Comment by rosysong** [comment]
It's the difference between browsers that result in this issue, we will fix it later.

**Comment by SoraKasvgano** [comment]
@mygoare 皮肤

**Comment by rosysong** [comment]
@boktai1000  the new commit fix this issue in Firefox, enjoy it, thanks!
