### ISSUE TITLE
怎么安装啊

### ISSUE THREAD

**Issue by joesdu** [rosywrt/luci-theme-rosy#35]
root@OpenWrt:~# opkg install luci-theme-rosy
Unknown package 'luci-theme-rosy'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-theme-rosy.
root@OpenWrt:~# 

这么装报错

**Comment by hbl0307106015** [comment]
你是用那个版本的openwrt??? opkg update更新一下源

**Comment by sky96111** [comment]
他没有发布编译后的版本，也没有上架官方源，只能下载源码用SDK编译

**Comment by joesdu** [comment]
> 
> 
> 你是用那个版本的openwrt??? opkg update更新一下源

我用的18.06.1小米青春版的路由器,我看了下源没看见这个的IPK

**Comment by joesdu** [comment]
> 
> 
> 他没有发布编译后的版本，也没有上架官方源，只能下载源码用SDK编译

自己编译太麻烦了,我没有Ubuntu的系统.

**Comment by sky96111** [comment]
> > 他没有发布编译后的版本，也没有上架官方源，只能下载源码用SDK编译
> 
> 自己编译太麻烦了,我没有Ubuntu的系统.

https://mega.nz/#!IQhnnC7L!DFuSCAVWJ-zZ7jlOmycPOBHZMqQHAgkZ0V0HeOjyxM0
我自己编译的

**Comment by joesdu** [comment]
> 
> 
> > > 他没有发布编译后的版本，也没有上架官方源，只能下载源码用SDK编译
> > 
> > 
> > 自己编译太麻烦了,我没有Ubuntu的系统.
> 
> https://mega.nz/#!IQhnnC7L!DFuSCAVWJ-zZ7jlOmycPOBHZMqQHAgkZ0V0HeOjyxM0
> 我自己编译的
我试试,3Q,链接好像失效了,你可以直接发我邮箱.dygood@outlook.com麻烦了

**Comment by rosysong** [comment]
@sky96111 @Dygood  你好， 请查看https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=342301&extra=&highlight=rosy&page=5， 62楼的
