### ISSUE TITLE
登陆界面排版

### ISSUE THREAD

**Issue by bits1125** [rosywrt/luci-theme-rosy#36]
登陆界面排版总感觉怪怪的，并非像作者主页截图那般，我觉得作者主页截图的登陆界面更好看。
还有就是我手机浏览器输入用户名和密码之后进入不了后台，不知道是不是我浏览器的问题。
![tim 20190113133922](https://user-images.githubusercontent.com/30818344/51082011-d9ba8d80-1738-11e9-8b0c-491d06dbcce9.png)

![tim 20190113133945](https://user-images.githubusercontent.com/30818344/51082014-e0e19b80-1738-11e9-90f0-13dfd2dd03c5.png)

**Comment by yglb** [comment]
请说一下你的浏览器，以及你使用的是否是openwrt

**Comment by hbl0307106015** [comment]
@iwowcn  如果你是从源码编译过来的, 请更新源码到最新并且确保你使用的浏览器缓存已经清除, 
还须注意的是, 确保你的SDK是官方openwrt18.06或者master分支以上版本,

**Comment by bits1125** [comment]
> @iwowcn 如果你是从源码编译过来的, 请更新源码到最新并且确保你使用的浏览器缓存已经清除,
> 还须注意的是, 确保你的SDK是官方openwrt18.06或者master分支以上版本,

Chromium 70.0.3538.110 64bit
https://github.com/coolsnowwolf/lede

源码已是最新，然后编译。

**Comment by rosysong** [comment]
@iwowcn  抱歉， 这是lede的代码， 请从 https://github.com/openwrt/openwrt 编译

**Comment by bits1125** [comment]
> @iwowcn 抱歉， 这是lede的代码， 请从 https://github.com/openwrt/openwrt 编译

看来暂时无解了 因为我平时都编译lede

**Comment by gxbyws** [comment]
我的登录界面跟图一一样，我用拙劣的jQuery修改了一下/www/luci-static/rosy/js/script.js，恢复了图二样式。增加了两行：
```
(function ($) {
    ...

    $('input[value="登录"]').parent('div').addClass('cbi-page-actions');
    $('fieldset').css('border-width', '0');
})(jQuery);
```

**Comment by hbl0307106015** [comment]
@gxbyws 你可以提交PR给lede或者其他代码仓库的maintainer
