### ISSUE TITLE
Some customized public pages may have no authenticate sessions which results a login background there.

### ISSUE THREAD

**Issue by shawnchain** [rosywrt/luci-theme-rosy#37]
https://github.com/rosywrt/luci-theme-rosy/blob/349901073d05a2fb330ca7bdc2dee93ebbaded94/luci-theme-rosy/luasrc/view/themes/rosy/header.htm#L236

**Comment by yglb** [comment]
This is a unique class name for each interface to modify the unique style of some interfaces.
@shawnchain

**Comment by hbl0307106015** [comment]
@shawnchain  You'd better open a issue to openwrt official.

**Comment by shawnchain** [comment]
我来解释一下这个问题。
现在的代码，是基于一个假设：所有的页面都需要登录才能访问。
于是问题来了：
假设你有两个页面A和B。其中A希望是用户无需登录就可以看到，而B则是要求登录才可以访问。那么在上面这一行代码判断中：
```<% if luci.dispatcher.context.authsession then %>logged-in<% end %>">``` 会导致A/B页面有不同的风格。而事实上，可能我们希望A和B页面都有相同的式样外观。

**Comment by yglb** [comment]
> 我来解释一下这个问题。
> 现在的代码，是基于一个假设：所有的页面都需要登录才能访问。
> 于是问题来了：
> 假设你有两个页面A和B。其中A希望是用户无需登录就可以看到，而B则是要求登录才可以访问。那么在上面这一行代码判断中：
> `<% if luci.dispatcher.context.authsession then %>logged-in<% end %>">` 会导致A/B页面有不同的风格。而事实上，可能我们希望A和B页面都有相同的式样外观。

大概明白你的意思了, 且容我先想想应该怎么解决这个问题, 谢谢提醒

**Comment by shawnchain** [comment]
搭车问个问题，master和18.06-branch上的rosy-theme有啥差别吗？

**Comment by rosysong** [comment]
源码有差别， 外观基本无差别

**Comment by shawnchain** [comment]
#2c4204f 
```Showing  with 895 additions and 1,137 deletions.```

最近的两个提交改动有点大啊，而且是在18.06分支，请问是重写了cascade.js ?

**Comment by hbl0307106015** [comment]
对代码进行了整理, 调整了部分细节, 修复了些bug. :-)  如何? 有问题吗? @shawnchain
