### ISSUE TITLE
Changes from openwrt/luci not making their way back to this repository

### ISSUE THREAD

**Issue by boktai1000** [rosywrt/luci-theme-rosy#39]
Hi,

This is more of a question than a problem - but it seems some of the fixes for Rosy mentioned here are being fixed in the OpenWrt Luci repository, but it doesn't seem like the commits are making their way back here.

For example:

- https://github.com/openwrt/luci/commit/714a48e6caffddf43db4c9b6911cac3bcf622ac6#diff-4b777d7baa620163fb6f43d2b14c748c
- https://github.com/openwrt/luci/commit/eb3976c64af6d2d3c67fd255ce9420c28b176392#diff-4b777d7baa620163fb6f43d2b14c748c
- https://github.com/openwrt/luci/commit/fa407b036a70067eb7de6912644b98fe0c18b642#diff-4b777d7baa620163fb6f43d2b14c748c
- https://github.com/openwrt/luci/commit/57dcdd2b847126007bf5b5b2340362ac7198d52a#diff-4b777d7baa620163fb6f43d2b14c748c
- https://github.com/openwrt/luci/commit/a5e1e86ba51ec6a6f08f45497c1ebbb959515101#diff-4b777d7baa620163fb6f43d2b14c748c

Maybe you can help me understand better, should we instead be using openwrt/luci instead for your changes? Maybe these changes are specific to OpenWrt and not here? 

I have been watching this repository for commits and fixes, but have noticed that it appears some of them only get submitted to openwrt and don't make there way back here.

Hopefully this makes sense, and its possible I simply don't have a firm grasp on the difference between the two repositories. It's something I've been thinking about though and thought I'd ask, feel free to close out this issue if necessary but a response would be appreciated. Thank you!

**Comment by rosysong** [comment]
Please use openwrt/luci, this repository is only for backward compatibility, such as 18.06 branch. Thanks for your question.
