### ISSUE TITLE
主题显示不正常

### ISSUE THREAD

**Issue by fuqiang03** [rosywrt/luci-theme-rosy#4]
openwrt 18.06 最新源码 wrt1900acs 显示不正常 
![qq 20180915140850](https://user-images.githubusercontent.com/26851715/45583252-f95bb980-b8f0-11e8-9ffd-ee7b4443db9e.png)
![qq 20180915140936](https://user-images.githubusercontent.com/26851715/45583253-fcef4080-b8f0-11e8-865a-aa05660422fb.png)
![qq 20180915140950](https://user-images.githubusercontent.com/26851715/45583254-fe206d80-b8f0-11e8-9bd4-3331a0ece903.png)

**Comment by rosysong** [comment]
谢谢你的反馈，已更新一版，修复大部分圆角问题。有问题随时在issue提

**Comment by fuqiang03** [comment]
![qq 20180922191453](https://user-images.githubusercontent.com/26851715/45916774-f8e99280-be9d-11e8-865e-b93ba2cd5d7d.png)
![qq 20180922193026](https://user-images.githubusercontent.com/26851715/45916776-fc7d1980-be9d-11e8-8030-10ba0e39b56b.png)
这个版本好多了 难得的openwrt主题 
第一个图小问题  数字409底部被吃掉了
第二个图如果插件过多没有滚动条 无法保存左侧栏的 插件停留位置 
感觉 主题的 布局好像对不上位置

**Comment by rosysong** [comment]
你好，第一个问题我们核实后会立即修复， 关于导航栏滚动条的建议，我们还在征集意见中，具体采纳与否尚未有定论， 敬请留意后续更新。
