### ISSUE TITLE
configure Firewall - Port Forwards - Formatting issue

### ISSUE THREAD

**Issue by olimpiumarius** [rosywrt/luci-theme-rosy#42]
SNAPSHOT r8392+863-3dba852547 / LuCI Master (git-19.026.58450-d6ae363)
Kernel Version 4.14.97
![capture](https://user-images.githubusercontent.com/34411358/52207214-5d255580-2885-11e9-857a-1bb5f16da514.PNG)
![capture png2](https://user-images.githubusercontent.com/34411358/52207215-5dbdec00-2885-11e9-999d-0b1b60ed7ba6.PNG)

**Comment by rosysong** [comment]
fixed, please update your code.
