### ISSUE TITLE
Sidebar not show in chrome on Android

### ISSUE THREAD

**Issue by JanKiel2000** [rosywrt/luci-theme-rosy#43]
Hello.
How do I use a mobile browser, for example "chrome" on my smatphone, there will not be a "sidebar" when I press the icon on the left. Navigating the menu is not possible. The "material" works well ...

Steel rat.

**Comment by rosysong** [comment]
We will fix the issue this month, thanks for your feedback.

**Comment by rosysong** [comment]
fixed, please update your code!
