### ISSUE TITLE
Menu display offset

### ISSUE THREAD

**Issue by pintopwnie** [rosywrt/luci-theme-rosy#46]
On LEDE/OPENWRT Rango wrt3200ACM the menu on the left side covers the updates running in the background. The updates should be visible in the center.

**Comment by rosysong** [comment]
Could you tell me your version of Openwrt ? master or 18.06 ?
And your browser, mobile phone or PC ? Showing A snapshot would be great. Thanks! @pintopwnie

**Comment by boktai1000** [comment]
It looks like the user @pintopwnie posted this over on the OpenWrt forums here:
- https://forum.openwrt.org/t/davidc502-wrt1200ac-wrt1900acx-wrt3200acm-wrt32x-builds/15839/1749

Based on the information provided, it appears this version of OpenWrt was built on 2019-02-09 15:22 from master (denoted from r9287 in the screenshot, in reference to the build number for the firmware they are running)

Screenshot below:
![image](https://user-images.githubusercontent.com/9054563/53765554-f439f900-3e95-11e9-8bc8-89636d6d6ce3.png)

Hopefully this can give you a headstart in tracking down the problem @rosysong - if you need more information maybe @pintopwnie can follow up further with you.

**Comment by rosysong** [comment]
@pintopwnie @boktai1000  Update your source code, if it doesn't work, please tell me the detailed steps to reproduce this problem, thanks!

**Comment by pintopwnie** [comment]
Model: Linksys WRT3200ACM
Architecture: ARMv7 Processor rev 1 (v7l)
Firmware Version: Lede SNAPSHOT r8614-78ca6a5578 / LuCI Master (git-18.333.34665-4f2b80e)
Kernel Version:4.14.82
Browser: Firefox 65.0.1 (64-bit)
![screenshot from 2019-03-07 11-00-58](https://user-images.githubusercontent.com/23638185/53948553-ff706d00-40bf-11e9-84a5-912103901c4a.png)
Additional info: I just downloaded Davidc502's latest build and updated it. Still has this issue. Also, this issue is not present in the wrt32X. I have the latest Davidc502 and this only happens with the wrt3200acm. Thanks.

**Comment by rosysong** [comment]
@pintopwnie  I am not sure whether the latest build from Davidc502 is up to date. It is strongly recommended that clone and build the image by yourself. 
openwrt : https://github.com/openwrt/openwrt.git

**Comment by boktai1000** [comment]
@pintopwnie the version of the Kernel from Davidc502 build should actually be 4.14.103, but you mention 4.14.82 in your post. I would double check and re-flash the latest build from him to be sure. Please see https://dc502wrt.org/ to validate the Kernel for the latest image (Release date of March 2nd 2019)

Some other things to note:
- There are two partitions on the wrt3200acm and wrt32x, and your previous image is installed on it. Maybe it's possible that you're booted in your old version still? If you want to be sure that you have the latest version installed to both, flash both partitions
- I would also try an NVRAM clear / Factory Default after flashing the latest version just to ensure.

Take a look at that and report back.

Update: Your Kernel version of 4.14.82 appears to match build r8614 (release date of December 1st 2018) at least which I was able to locate from the forum post https://forum.openwrt.org/t/davidc502-wrt1200ac-wrt1900acx-wrt3200acm-wrt32x-builds/15839/1185

In the known issues with this release:

> Known issues:
LuCi -- Clicking "update lists" in the Software section will error out. The work around is to log into the router via ssh, and issue the command "opkg update". Then go back to LuCi > Software, and it will work as it should.

So in addition to this version including an older version of Rosy, it has known issues with it. I would advise ensuring you are upgrading your firmware properly by double checking to make sure the version matches afterwards as should be expected (and maybe do a double upgrade as I mentioned above) before opening bugs on the tracker which may already have been squashed.

**Comment by rosysong** [comment]
Currently, we don't maintain the issues led by images built from other source except [openwrt](https://github.com/openwrt/openwrt) and [luci](https://github.com/openwrt/luci).
Please report bugs to the corresponding owner. @pintopwnie  Thanks!
