### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by lm317379829** [rosywrt/luci-theme-rosy#5]
反馈下，在分辨率比较低的手机上720P，VIA浏览器上体验不佳，右上角侧边栏点出后 状态、系统、服务、网络展开后显示不完全，而且无法拖动，同时，最下方的选项有时会与退出重叠，导致比如想选择网络，却点成退出了。
在楼下附上了图片。

**Comment by lm317379829** [comment]
![gif](https://user-images.githubusercontent.com/25142345/45790106-d1d06c80-bcb5-11e8-814d-6347f23f737a.gif)

**Comment by rosysong** [comment]
谢谢你的反馈， 该问题在新版已解决， 我没来得及回复。有问题随时在issue提， 谢谢
