### ISSUE TITLE
配置页面标签的水平padding应该大一点

### ISSUE THREAD

**Issue by WuSiYu** [rosywrt/luci-theme-rosy#51]
这个主题总体来讲还是相当漂亮的，提个小建议，有些带标签的配置页面的那些标签，左右的padding有点太小了，显得会很挤，不太美观，希望可以加大一点。

现在：
![{1B856B92-F132-4E29-80EA-F8383ECD09F6} png](https://user-images.githubusercontent.com/6263652/54915195-90a16980-4f31-11e9-8c26-ca64bddb25d8.jpg)

加大之后：
![{BB3D4875-0482-4948-B88B-4CD6861288B1} png](https://user-images.githubusercontent.com/6263652/54915231-a57dfd00-4f31-11e9-8a40-a9c0a4564b0e.jpg)

**Comment by yglb** [comment]
嗯的，我也觉得，只是最近时间比较紧急，很多细节没来得及修改

**Comment by rosysong** [comment]
@WuSiYu  谢谢你的建议，欢迎给我们多提意见。

**Comment by rosysong** [comment]
@yglb  @WuSiYu   https://github.com/openwrt/luci/pull/2663   Fixed!
