### ISSUE TITLE
ComboBox with MAC or IP problem

### ISSUE THREAD

**Issue by JanKiel2000** [rosywrt/luci-theme-rosy#52]
Hello. There is a problem with "ComboBox". The list goes below the frame and you can not select entries from the list below. There is no way to mark anything for the last field.
Regards Steel Rat.
![Scrreen1](https://user-images.githubusercontent.com/27873081/55252304-dff9d980-5252-11e9-88f6-7dfa06ccfe7a.png)

**Comment by hbl0307106015** [comment]
@steelrat2000  Does your source code base on master branch of openwrt/openwrt and openwrt/luci ? We fixed this issue many days agao. Thanks!

**Comment by JanKiel2000** [comment]
Yes. I use rosy from master branch. I myself compiles images for WRT3200ACM. Other "Combobox" work well. Only those related to MAC or IP.
Regards Steel Rat.

**Comment by rosysong** [comment]
Fixed, thanks!

https://github.com/openwrt/luci/pull/2663
