### ISSUE TITLE
交换机页面下配置显示过大

### ISSUE THREAD

**Issue by nature2608** [rosywrt/luci-theme-rosy#53]
![rosy](https://user-images.githubusercontent.com/32662472/57206185-84133500-6ff6-11e9-92bf-1146ce62ae02.png)
![material](https://user-images.githubusercontent.com/32662472/57206186-86758f00-6ff6-11e9-923a-1d63c5c3b06f.png)

**Comment by rosysong** [comment]
已修复，https://github.com/openwrt/luci/pull/2688

**Comment by nature2608** [comment]
感谢！，可能是因为我下载的是这个页面没有同步的源码。
