### ISSUE TITLE
Force some sans-serif font

### ISSUE THREAD

**Issue by mistepien** [rosywrt/luci-theme-rosy#55]
It would be great if the font was some sans-serif font, just like for instance in ubiquiti controller or bootstrap default openwrt theme.

**Comment by rosysong** [comment]
thanks for your advice !

**Comment by seandex** [comment]
I do not want official OpenWRT fonts on a custom theme.

San serif does not match with the current rosy theme.
current san serif is ugly in design-wise on the rosy theme.

How can I change the san serif font to other fonts? just replace ttf?

I don't want any German parts in my Italian sports car.
