### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by tuanqing** [rosywrt/luci-theme-rosy#7]
在显示系统进程时，若命令名(如nlbwmon)过长则会导致显示异常。
![screencapture-192-168-1-1-cgi-bin-luci-admin-status-processes-2018-09-24-11_10_51](https://user-images.githubusercontent.com/32225473/45936553-95b94680-bfea-11e8-8f91-d5587aa879a5.png)

**Comment by rosysong** [comment]
@tuanqing 谢谢你的反馈， 请问同等情况下， 官方其他主题会有类似问题吗？ 能否试试看

**Comment by rosysong** [comment]
你好， 新版本已经修复该问题， 请查验一下， 谢谢

**Comment by tuanqing** [comment]
@rosysong 好像并没有解决
![default](https://user-images.githubusercontent.com/32225473/46612336-d49ae080-cb42-11e8-86c9-62c84ab6d1ee.png)

**Comment by yglb** [comment]
你好, 新版本已经修复好了这个问题, 请检查一下, 谢谢

**Comment by yglb** [comment]
你好, 新版本已修复该问题, 请检查一下你的代码, 谢谢
![image](https://user-images.githubusercontent.com/39110824/46653954-0ad76f00-cbda-11e8-8081-ba64e1f4dd72.png)

**Comment by tuanqing** [comment]
难道是我luci版本的问题？我用的18.138.53009-80cb4fe

**Comment by tuanqing** [comment]
好的 感谢提供这么好的主题 @rosysong
